ALTER TABLE public.links ADD COLUMN IF NOT EXISTS og_title TEXT DEFAULT NULL;
ALTER TABLE public.links ADD COLUMN IF NOT EXISTS og_description TEXT DEFAULT NULL;
ALTER TABLE public.links ADD COLUMN IF NOT EXISTS og_image_url TEXT DEFAULT NULL;
